env:
  node: true
  browser: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/no-relative-packages:
    - off
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
